import AntdProvider from "@/app/lib/AntdProvider";
import LoginRedirectHandler from "@/app/lib/LoginRedirectHandler";
import ReactQueryClientProvider from "@/app/lib/ReactQueryClientProvider";
import { Layout } from "antd";
import { Content } from "antd/es/layout/layout";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Upwork CRM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReactQueryClientProvider>
          <AntdProvider>
            <LoginRedirectHandler>
              <Layout style={{ minHeight: "100vh" }}>
                <Content
                  style={{ padding: "30px", maxWidth: "1200px", margin: "auto", width: "100%", display: "flex", flexDirection: "column" }}
              >
                {children}
                </Content>
              </Layout>
            </LoginRedirectHandler>
          </AntdProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
