import AppHeader from "@/app/AppHeader";
import AntdProvider from "@/app/lib/AntdProvider";
import ReactQueryClientProvider from "@/app/lib/ReactQueryClientProvider";
import { Layout } from "antd";
import { Content } from "antd/es/layout/layout";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthRedirect from "@/app/login/AuthRedirect";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Upwork CRM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReactQueryClientProvider>
          <AntdProvider>
            <AuthRedirect>
              <Layout style={{ minHeight: "100vh" }}>
                <AppHeader />
                <Content
                  style={{
                    maxWidth: "1200px",
                    width: "100%",
                    margin: "auto",
                    padding: "30px",
                    display: "flex",
                    flexDirection: "column",
                  }}
                >
                  {children}
                </Content>
              </Layout>
            </AuthRedirect>
          </AntdProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
